---
name: Authen-Simple-PAM
version: 0.2
author:
  - 'Christian Hansen C<ch@ngmedia.com>'
abstract: Simple PAM authentication
license: perl
requires:
  Authen::PAM: 0
  Authen::Simple: 0
provides:
  Authen::Simple::PAM:
    file: lib/Authen/Simple/PAM.pm
    version: 0.2
generated_by: Module::Build version 0.2611
